# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Bhe's Blog
subtitle: Bhe's Blog
description: ''
keywords:
author: Bhe Hongtyu
language: zh_CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://io.bhe.ink
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags

archive_dir: archives
## archive as index

category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "google*.html"

# Writing
#new_post_name: :title.md # File name of new posts
new_post_name: :year-:month-:day-:title.md # for octopress
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false 
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: false
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  #path: 'archives'
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
#theme: apollo
theme: next
theme_config:
  scheme: Mist
  menu:
    home: / || fa fa-home
    archives: /archives/ || fa fa-archive
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    #about: /about/ || fa fa-user
  darkmode: true
  social:
    GitHub: https://github.com/hitsmaxft || fab fa-github
    Twitter: https://twitter.com/hitsmaxft|| fab fa-twitter
  disqus:
    enable: true
    shortname: bhehontyublogging
    count: true
  font:
    enable: true
    global:
      size: 0.9
    posts:
      external: true
      family: LXGW wenkai,LXGW WenKai Lite, Lato, PingFang SC, Microsoft YaHei, sans-serif 
  google_analytics:
    tracking_id: UA-42604344-1
    # By default, NexT will load an external gtag.js script on your site.
    # If you only need the pageview feature, set the following option to true to get a better performance.
    only_pageview: false
  index_with_subtitle: true
  # see https://search.google.com/search-console/ownership?resource_id=https%3A%2F%2Fio.bhe.ink%2F
  google_site_verification: uLR4tiR7G944Hw8MS8h3bqSW0xN_C1OlwZwhiWplfWI
  baidu_site_verification: codeva-idh14paPwc
  back2top:
    enable: true
  github_banner:
    enable: true
    permalink: https://github.com/hitsmaxft
  codeblock:
    ## docs: https://theme-next.js.org/highlight/
    prism:
      #light: prism-solarizedlight
      #dark: prism-dark
      light: prism-material-oceanic
      dark: prism-material-oceanic

# SEO
## automatically generate sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false

robotstxt:
  useragent: "*"
  allow:
  - /
  sitemap: https://io.bhe.ink/sitemap.xml
feed:
  type: rss2
  path: rss2.xml
  limit: 20

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:hitsmaxft/hitsmaxft.github.io.git
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
filter:
  # web font filter for wenkai
  bheWebFontFilter: scripts/webfont.filter.js


