menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/hitsmaxft
    GitHub: https://github.com/hitsmaxft
    Rss: /atom.xml

archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: bhehontyublogging
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
