name: Pages

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "publish" ]
  repository_dispatch:
    types: [blog-publish]
  workflow_dispatch:
jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout blog source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }} # If your repository depends on submodule, please see: https://github.com/actions/checkout
          repository: hitsmaxft/blog-source
          fetch-depth: 0
          fetch-tags: false
          ref: 'master'
          submodules: recursive
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./public